version: 2.1

jobs:
  build_and_test:
    docker: 
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
